before_script:
  - export APP_VERSION=$(git describe --always --dirty)
  - export STACK_PHP_IMAGE=registry/namespace/app:${APP_VERSION}
  - export ISOLATION=buildref${CI_BUILD_REF}$(echo ${CI_BUILD_REF_NAME} | tr -dc '[:alnum:]\n\r' | tr '[:upper:]' '[:lower:]')
  - export COMPOSE_PROJECT_NAME=${ISOLATION}

stages:
  - build
  - release
  - cleanup

build:
  stage: build
  script:
    - docker-compose build --pull

release:
  stage: release
  script:
    - docker-compose push

cleanup:
  stage: cleanup
  script:
    - docker-compose down -v