version: '2'
services:
  php:
    build:
      dockerfile: Dockerfile
      context: .
    depends_on:
      - db
    environment:
      - MYSQL_ROOT_PASSWORD=secret
  db:
    #command: --character-set-server=utf8 --collation-server=utf8_general_ci
    image: percona:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=secret
    ports:
      - '3306'